services:
  postgres:
    image: postgres:16
    container_name: jobhelper-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: jobhelper
      POSTGRES_PASSWORD: Alireza@GBC!123
      POSTGRES_DB: jobhelper_ai

    ports:
      - "9999:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: jobhelper-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jobhelper.ai
      PGADMIN_DEFAULT_PASSWORD: Alireza@GBC!123

    ports:
      - "5050:80"

    depends_on:
      - postgres

    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    external: true
    name: jobhelperai_postgres_data

  pgadmin_data:
    external: true
    name: jobhelperai_pgadmin_data